# this component will thank the user for playing when they want to leave
print(" ********** ")
print("***thanks***")
print(" ********** ")
print()
print(":::::::::::::")
print(":::::for:::::")
print(":::::::::::::")
print()
print("#############")
print("###playing###")
print("#############")
